### PR TITLE
COMP: Fix build against Qt 4.8

### PR DESCRIPTION
**Pull request by johan-andruejol**
This failed to compile in the
precompiled. moc_PythonQtStdDecorators.cpp.  This function seems to be
only stub so removing it.

### CODE REVIEW

**Comment by patmarion** [comment]
Tested this on my Linux build with Qt 4.6.3.  Works fine.

**Comment by jeinarsson** [comment]
Compiles on win7/msvc2008/python2.7/qt4.8 with patch. Had to disable XmlPatterns wrapper though.

**Comment by thewtex** [comment]
This patch worked for me too against 4.8.1 on linux.

I don't see any contact information on the PythonQt website.  Does anyone know who to contact?

**Comment by jcfr** [comment]
Hi Folks, 

Upstream PythonQt (aka Florian) has integrated our patches to enable `CMake` based build. (See [r200](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=200), [r201](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=201), [r202](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=202), [r204](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=204), [r205](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=205))

He also added a mechanism allowing to registered external wrapping mechanism (i.e. VTK). See  [r206](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=206))

In addition to various bug fixes, support for Qt 4.8 has also been added upstream (See [r213](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=213) and  [r226](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=226)) 

Given these information, here is the plan:
- To ensure that existing project relying on the `patched` branch can be built against CTK/PythonQt, the `patched` branch will be kept as it is. 
- A new branch named `patched-2` will be added, it will be based on the most recent PythonQt (very probably [r228](http://pythonqt.svn.sourceforge.net/viewvc/pythonqt?view=revision&revision=228))
- Regarding the _glue code_ enabling the use of PythonQt with VTK based project. I envision two options:
  *\*  Add it inside CTK itself (under [Libs/Scripting/Python/Core](https://github.com/commontk/CTK/tree/master/Libs/Scripting/Python/Core) or [Libs/Visualization/VTK/Scripting](https://github.com/commontk/CTK/tree/master/Libs/Visualization/VTK/Scripting). 
  *\* Create a separate project named for example `PythonQtVTKWrapper` that will host the code.

Let me know what you all think ? 

Jc

**Comment by thewtex** [comment]
> Let me know what you all think ? 

Thanks for your work on this!

I'm late to the show, but for my information; if the CMake changes have been merged upstream, what will be the difference between patched-2 and upstream HEAD?

Thanks,
Matt

**Comment by jcfr** [comment]
Hi @thewtex, 

Good point. Hopefully, it shouldn't be needed. I am just anticipating some possible specific tweak before backporting changes upstream. `patched-2` could be seen as a staging area before the change are integrated into the official repo. 

Next week, I will be in Boston for the [CTK hackfest](http://www.commontk.org/index.php/CTK-Hackfest-Jul-2012) and i will be working on that.

Jc

**Comment by thewtex** [comment]
Cool!

On Wed, Jul 4, 2012 at 9:16 PM, Jean-Christophe Fillion-Robin
reply@reply.github.com
wrote:

**Comment by jcfr** [comment]
See https://github.com/commontk/PythonQt#patched-2

**Comment by thewtex** [comment]
Excellence.

On Tue, Jul 10, 2012 at 9:15 PM, Jean-Christophe Fillion-Robin
reply@reply.github.com
wrote:

**Pull request closed without merging**
