### PR TITLE
added missing header and travis/osx

### PR DESCRIPTION
**Pull request by iltommi**
I've added a header file (`src/gui/PythonQtScriptingConsole.h`) in the install.

I also added a travis file as first attempt to continuous integration. 
It's not that much because it just check the compilation on osx, but it works. Anwone willing to add other os might find it helpful.

here is a sample of the pytohnqt compilation for osx : https://travis-ci.org/iltommi/PythonQt

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for resuming work on this :+1:

**Comment by jcfr** [comment]
As a side note, branch patched-07 has been updated to work against the latest version of Qt and PythonQt. When things are stable ... we will contribute patches in upstream PythonQt.

**Comment by iltommi** [comment]
I've seen and I tried to get that and include in travis-ci, but unfortunately I have some problems with the linux build environment on travis which uses QT 5.2 and that version is really strange (the webkit is missing...)

**Comment by jcfr** [comment]
@iltommi  Thanks for the patches. 

Based on the history of the branch, it looks like you need to support Qt5. If this is the case, I suggest you base your work on `patched-8` branch.

If only need to support Qt4, rebasing your changes on top of `patched-6` would be sensible.

Reading here provides info on which branch are the current ones: https://github.com/commontk/PythonQt

**Comment by iltommi** [comment]
ok I'll jump to patched-8.

I will add an issue I just discovered :)

**Pull request closed without merging**
