### PR TITLE
[patched-9] Backport recent changes from `MeVisLab/pythonqt`

### PR DESCRIPTION
**Pull request by jcfr**
Meticulous backport of all recent changes introduced in https://github.com/MeVisLab/pythonqt/

Commit impacting only the PythonQt library are prefix with `[Backport]` the one impacting only the generator are prefixed with `[Backport generator]`.

Changes related to the GitHub workflow continuous  integration have not been backported.

### CODE REVIEW

**Comment by jcfr** [comment]
Related to:
* https://github.com/commontk/CTK/pull/1159

@jamesobutler this is complementary to the integration of the generated 5.15 wrappers.

**Comment by jamesobutler** [comment]
Is there a reason to backport all these commits onto the existing `patched-9` branch rather than creating a new branch with a new base and putting the CommonTK customizations on top (like https://github.com/jamesobutler/PythonQt/tree/patched-11)?

**Comment by jcfr** [comment]
Few days ago, I was initially backporting selected commits and ended up integrating them all.

It was also the opportunity to review all the ones updating PythonQt library and identify the one I still need to upstream.

**Comment by jamesobutler** [comment]
I can try this branch in the context of 3D Slicer. Have you done this already? 

One change I needed to do when I initially brought `patched-9` customizations on top of latest MeVisLab/PythonQt head, I needed https://github.com/jamesobutler/PythonQt/commit/baca87f05c0b50e20dfacd4191fe688b1604ef22 to make sure there wasn’t a crash on exit.

**Review by jamesobutler — COMMENTED** [review]
@jcfr I have tested this branch in the context of 3D Slicer and I am facing the same crash on exit that I was observing in my work. With https://github.com/jamesobutler/PythonQt/commit/baca87f05c0b50e20dfacd4191fe688b1604ef22 added onto this branch, 3D Slicer no longer crashes on exit.

**Pull request merged**
