### PR TITLE
Python qt3 upgrade

### PR DESCRIPTION
**Pull request by ericheim**
Upgraded to PythonQt3.0 release from sourceforge. Added CMakeLists.txt for Qt4 & Qt5. TODO: Forcing Qt4.7 if Qt4.8 is present due to faulty generated 4.7 headers in the PythonQt project.

### CODE REVIEW

**Comment by jcfr** [comment]
@eric-h  Thanks for your contribution :+1: 

Could you (1) base your topic on top of the new branch `patched-5` I just pushed and (2) consider cherry-picking changes from @Alzathar posted in #22 ? Thanks  

Related issue(s): #13

**Comment by ericheim** [comment]
@jcfr rebased to patched-5 branch and added "set(QT_USE_QTTEST ${BUILD_TESTING})" for Qt4 from the @Alzathar repository

**Comment by ericheim** [comment]
Fixed win32 build.

**Comment by jcfr** [comment]
Hi Eric,
Considering i ll be travelling during the coming two weeks. Unless an other
CTK member want to review and integrate,  final integration will wait a
little bit.
Thanks for your patience,
Jc

##

**Comment by AndreasFetzer** [comment]
@jcfr do you think this pullrequest is ready for being merged?
We would like to include the proposed changes in MITK.

**Comment by jcfr** [comment]
@AndreasFetzer Let's close this PR. There is now the `patched-6` branch. See [1] 

After integrating in `patched-6` the recent fixes done by @msmolens  on `patched-5`, it should be good.

[1] https://github.com/commontk/PythonQt/commits/patched-6

**Comment by AndreasFetzer** [comment]
@jcfr closing the PR is ok for us. Can you estimate when the qt5 support will be integrated into ctk/PythonQt?

**Comment by jcfr** [comment]
Closing this PR. Superseded by #39

**Pull request closed without merging**
